[server]
headless = true
enableCORS = false
port = 8501
runOnSave = true  # optional: auto-reload when code changes (useful during dev)

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

