[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#00BFFF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[ui]
page_title = "Stock Trend Predictor"
page_icon = "📈"
